dairy_site/urls.py
from django.urls import path,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',views.homePage,name='homepage'),
    path('customer/',include('customer.urls',namespace='cust')),
    path('item/',include('item_register.urls',namespace='item')),
    path('pay/',include('payment.urls',namespace='payment')),
    path('report/',include('reports.urls',namespace='report')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'
urlpatterns = [
    path('pay/',views.AddTransection.as_view(),name='pay'),
    path('view/',views.ViewTransection.as_view(),name='view'),
    path('delete/<int:pk>',views.DeleteTransection.as_view(),name='delete'),
    path('api/balance',views.giveBalance,name='apibalance'),
]

payment/models.py
from django.db import models
from customer.models import Customer
from django.utils import timezone
from item_register.models import Bill
from customer.models import Customer
from django.db.models.signals import pre_delete,post_save,pre_save,pre_delete
from django.dispatch import receiver

class Transections(models.Model):
    date = models.DateField(default=timezone.now,blank=True)
    trans_id = models.CharField(max_length=10,unique=True,null=True)
    customer = models.ForeignKey(Customer,on_delete=models.PROTECT)
    credit = models.BooleanField(default=False)
    amount = models.IntegerField()
    remarks = models.CharField(max_length=255,blank=True,null=True)

    class Meta:
        ordering = ['date']

class Balance(models.Model):
    date = models.DateField(default=timezone.now,blank=True)
    customer = models.ForeignKey(Customer,on_delete=models.PROTECT)
    balance = models.IntegerField()

@receiver(post_save,sender=Customer)
def addCustomertobalance(sender,**kwargs):
    if kwargs['created']:
        data = kwargs['instance']
        Balance.objects.create(
            customer = data,
            balance = 0
        )
    return 0

@receiver(pre_delete,sender=Transections)
def removeBalance(sender,**kwargs):
    obj = kwargs['instance']
    balance = Balance.objects.get(customer=obj.customer)
    if obj.credit:
        balance.balance -= obj.amount
    else:
        balance.balance += obj.amount
    balance.save()


@receiver(post_save,sender=Transections)
def updateBalance(sender,**kwargs):
    if kwargs['created']:
        obj = kwargs['instance']
        balance = Balance.objects.get(customer=obj.customer)
        if obj.credit:
            balance.balance += obj.amount
        else:
            balance.balance -= obj.amount
        balance.save()

@receiver(pre_delete,sender=Bill)
def billbalanceremove(sender,**kwargs):
    data = kwargs['instance']
    obj = Bill.objects.get(id=data.id)
    Transections.objects.get(trans_id = 'BL'+str(obj.bill_no)).delete()

payment/views.py
from django.shortcuts import render
from django.urls import  reverse_lazy
from django.views.generic import CreateView,UpdateView,DeleteView,ListView
from .models import Transections,Balance
from customer.models import Customer
from django.http import JsonResponse,HttpResponse
from django.core import serializers
import json
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


class AddTransection(LoginRequiredMixin,CreateView):
    model = Transections
    template_name = 'add_transection.html'
    success_url = '/'
    fields = ['date','customer','trans_id','credit','amount','remarks']

class ViewTransection(LoginRequiredMixin,ListView):
    model = Transections
    template_name = 'view_transections.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ViewTransection, self).get_context_data(**kwargs)
        query = Transections.objects.exclude(trans_id__icontains='BL').order_by('date')
        paginator = Paginator(query, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            file_exams = paginator.page(page)
        except PageNotAnInteger:
            file_exams = paginator.page(1)
        except EmptyPage:
            file_exams = paginator.page(paginator.num_pages)

        context['object_list'] = file_exams
        return context

class DeleteTransection(LoginRequiredMixin,DeleteView):
    model = Transections
    template_name = 'delete_transection.html'
    success_url = reverse_lazy('item:blank')

@login_required
def giveBalance(request):
    if request.method == "GET":
        id = request.GET.get('id')
        try:
            id = int(id)
        except ValueError:
            return HttpResponse(json.dumps({'responce':0,'data':'Customer Name'}))
        if isinstance(id,int):
            cust = Customer.objects.filter(cust_id=int(id))
            if cust.exists():
                bal = Balance.objects.get(customer=cust[0])
                data = {
                    'responce':1,
                    'amount':bal.balance,
                    'name': str(bal.customer.name)+" / "+str(bal.customer.father_or_husband_name),
                    'id':bal.customer.id,
                }
                return HttpResponse(json.dumps(data))
            else:
                return HttpResponse(json.dumps({'responce':0,'data':'customer id not exists'}))
        else:
            return HttpResponse(json.dumps({'responce':0,'data':'enter integer value'}))

payment/templates/add_transection.html
{%extends 'base_templates/base.html'%}
{%block title%}Add Transection{%endblock%}
{%block content%}
<hr>
<div class="row mb-4">
  <div class="col-sm-12 text-center text-muted"> Add Transection</div>
</div>
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-8">
    <form class="needs-validation" novalidate  method="post">
      {%csrf_token%}
      {{ form.non_field_errors }}
      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="{{ form.date.id_for_label }}">Date</label>
          {{form.date}}
          {%if form.date.errors %}
            <div class="invalid-tooltip" style="display:block">
              {{ form.date.errors }}
            </div>
          {%endif%}
        </div>
        <div class="col-md-4 mb-3">
          <label for="{{ form.trans_id.id_for_label }}">Transection ID</label>
          {{form.trans_id}}
          {%if form.trans_id.errors %}
            <div class="invalid-tooltip" style="display:block">
              {{ form.trans_id.errors }}
            </div>
          {%endif%}
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="id_customer">Customer Id</label>
          <input type="number" class="form-control" id="customer_id" required>
          <input type="hidden" name="customer" value="{{form.customer.value}}" id="id_customer">
          {%if form.customer.errors %}
            <div class="invalid-tooltip" style="display:block">
              {{ form.customer.errors }}
            </div>
          {%endif%}
        </div>
        <div class="col-md-4 mb-3">
          <label for="validationTooltip02">Customer Name</label>
          <input type="text" class="form-control" value="customer name" style="color:blue" id="customer_name" disabled>
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="{{ form.amount.id_for_label }}">Amount</label>
          {{form.amount}}
          {%if form.amount.errors %}
            <div class="invalid-tooltip" style="display:block">
              {{ form.amount.errors }}
            </div>
          {%endif%}
        </div>
        <div class="col-md-4 mt-4 ml-2">
          {{ form.credit.errors }}
          <div class="custom-control custom-checkbox">
            {{form.credit}}
            <!-- <input type="checkbox" class="custom-control-input" id="id_credit" name="credit"> -->
            <label class="custom-control-label" for="{{ form.credit.id_for_label }}">Credit</label>
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-8 mb-3">
          <label for="{{ form.remarks.id_for_label }}">Remarks</label>
          {{form.remarks}}
          {%if form.remarks.errors %}
            <div class="invalid-tooltip" style="display:block">
              {{ form.remarks.errors }}
            </div>
          {%endif%}
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-8 text-right">
          <button class="btn btn-primary" type="submit">Submit form</button>
        </div>
      </div>
    </form>
  </div>
  <div class="col-sm-2"></div>
</div>
{%endblock%}
{%block script%}
<script type="text/javascript">
  $('#id_date').addClass('form-control')
  $('#id_remarks').addClass('form-control')
  $('#id_amount').addClass('form-control')
  $('#id_trans_id').addClass('form-control')
  $('#id_trans_id').prop('type','number')
  $('#id_credit').addClass('custom-control-input')

  var $initial = $('#id_customer');
  var typingTimer;                //timer identifier
  var doneTypingInterval = 300;  //time in ms, 5 second for example
  var $input = $('#customer_id');

  if ($initial.val()) {
    var $input = $('#id_customer');
    doneTyping();
    var $input = $('#customer_id');
    $input.val($initial.val())
  }
  //on keyup, start the countdown
  $input.on('keyup', function () {
    clearTimeout(typingTimer);
    typingTimer = setTimeout(doneTyping, doneTypingInterval);
  });

  //on keydown, clear the countdown
  $input.on('keydown', function () {
    clearTimeout(typingTimer);
  });

  //user is "finished typing," do something
  function doneTyping () {
    var id = $input.val();
    if (!id) {
      $('#customer_name').val('Customer Name');
      $('#customer_name').css('color','blue');
      $('#id_customer').val('None');
    }
    else {
      $.ajax({
          url: "{%url 'payment:apibalance'%}",
          data: {'id':id},
          datatype: 'json',
          success: function(data){
            var model = JSON.parse(data);
            if (model.responce) {
              $('#customer_name').val(model.name);
              $('#id_customer').val(model.id);
              $('#customer_name').css('color','green');
            }
            else {
              $('#id_customer').val('None');
              $('#customer_name').val(model.data);
              $('#Customer_name').css('color','red');
            }
          }
      });
    }
  }
</script>
{%endblock%}

payment/templates/delete_transection.html
{%extends 'base_templates/base_without_navbar.html'%}
{%block title%}Delete Transection{%endblock%}
{%block content%}
<form method="post" class="alert alert-danger">{% csrf_token %}
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Confirmation!</h4>
    <p>Are you sure you want to delete?</p>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">{{object.trans_id}}</li>
      <li class="list-group-item">{{object.customer.name}}/{{object.customer.father_or_husband_name}}</li>
      {%if object.credit%}
      <li class="list-group-item" style="color:green">{{object.amount}}</li>
      {%else%}
      <li class="list-group-item" style="color:red">{{object.amount}}</li>
      {%endif%}
    </ul>
    <hr>
    <input class="btn btn-danger" type="submit" value="Confirm">
  </div>
</form>
{%endblock%}

payment/templates/view_transections.html
{% extends 'base_templates/base.html'%}
{%block title%} Payment Reports {%endblock%}
{%block content%}
<style media="screen">
.table td, .table th {
  padding: 0.35rem;
  vertical-align: top;
  border-top: 1px solid #dee2e6;
}
</style>
<hr>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-1"></div>
      <div class="col-sm-10">
        <div class="row mb-3">
          <div class="col-sm-4 text-muted"><h4> Transections </h4></div>
          <div class="col-sm-4"></div>
        </div>
        <div class="row">
          <div class="table-responsive">
            <table class="table table-striped border-bottom" style="font-size:12px;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Date</th>
                  <th scope="col">Transection ID</th>
                  <th scope="col">Name</th>
                  <th scope="col">Credit</th>
                  <th scope="col">Debit</th>
                  <th scope="col">remarks</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                {% for trans in object_list %}
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                      <td>{{ trans.date }}</td>
                      <td>{{ trans.trans_id }} </td>
                      <td>{{trans.customer.name}}/{{trans.customer.father_or_husband_name}}</td>
                      {%if trans.credit %}
                        <td style="color:green;">{{trans.amount}}</td>
                        <td></td>
                      {%else%}
                        <td></td>
                        <td class="text-danger">{{trans.amount}}</td>
                      {%endif%}
                      <td>{{trans.remarks}}</td>
                      <td><span><i class="fa fa-trash" style="color:red" id='trans-{{trans.id}}' onclick="openform({{trans.id}})" data-url="{%url 'payment:delete' trans.id%}"></i></span></td>
                    </tr>
                {% empty %}
                    <tr><td colspan="8" class="text-center">No Transections yet.</td></tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="row">
          <nav aria-label="...">
            <ul class="pagination pagination-sm">
              {% for item in "x"|ljust:object_list.paginator.num_pages %}
                {%if forloop.counter == object_list.number %}
                  <li class="page-item disabled">
                    <a class="page-link" href="?page={{forloop.counter}}" tabindex="-1">{{forloop.counter}}</a>
                  </li>
                {%else%}
                  <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                {%endif%}
              {% endfor %}
            </ul>
          </nav>
        </div>
      </div>
      <div class="col-sm-1"></div>
    </div>
  </div>
{%endblock%}
{%block script%}
<script type="text/javascript">
  function openform(id){
    url = document.getElementById('trans-'+id).dataset.url
    newwindow = window.open(url,"Form","width=400,height=400,left=400,top=200");
    newwindow.loadData()
  }

  function loadData(){
    window.location.reload();
  }
</script>
{%endblock%}