dairy_site/urls.py
from django.urls import path,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',views.homePage,name='homepage'),
    path('customer/',include('customer.urls',namespace='cust')),
    path('item/',include('item_register.urls',namespace='item')),
    path('pay/',include('payment.urls',namespace='payment')),
    path('report/',include('reports.urls',namespace='report')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item_register/urls.py
from django.urls import path
from . import views

app_name='item_register'
urlpatterns = [
    path('add/',views.AddItem.as_view(),name='add'),
    path('view/',views.ViewItem.as_view(),name='view'),
    path('update/<int:pk>',views.UpdateItem.as_view(),name='update'),
    path('delete/<int:pk>',views.DeleteItem.as_view(),name='delete'),
    path('add_bill/',views.AddBill.as_view(),name='add_bill'),
    path('tempitem/',views.TempItemCreateView.as_view(),name='addtempitem'),
    path('tempitemupdate/<int:pk>',views.TempItemEditView.as_view(),name='edittempitem'),
    path('tempitemdelete/<int:pk>',views.TempItemDeleteView.as_view(),name='deletetempitem'),
    path('newbill/',views.NewBill,name='new_bill'),
    path('viewbills/',views.ViewBill.as_view(),name='view_bill'),
    path('deltebills/<int:pk>',views.DeleteBill.as_view(),name='delete_bill'),
    path('api/update',views.updateList,name='list'),
    path('blank/',views.blankPage,name='blank'),
    # path('stockregister/',views.StockRegister,name='stock_register'),
]

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'
urlpatterns = [
    path('pay/',views.AddTransection.as_view(),name='pay'),
    path('view/',views.ViewTransection.as_view(),name='view'),
    path('delete/<int:pk>',views.DeleteTransection.as_view(),name='delete'),
    path('api/balance',views.giveBalance,name='apibalance'),
]

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'
urlpatterns = [
    path('',views.LedgerQueryView.as_view(),name='report'),
    path('ledger/',views.ledgerView,name='list'),
]

templates/base_templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{%block title%}{%endblock%}</title>
		<link rel="stylesheet" type="text/css" href="{%static 'vendor/bootstrap/css/bootstrap.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{%static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
		{%block link%}{%endblock%}
	</head>
	<body  style="font-family:'Nunito Sans';letter-spacing: 1px;">
		{%include 'base_templates/navbar.html'%}
		<div class="container-fluid mb-3">
			{%block content%}
			{%endblock%}
		</div>
	</body>
	<script src="{%static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
	<script src="{%static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
	{%block script%}
	{%endblock%}
</html>

templates/base_templates/base_without_navbar.html
{%load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{%block title%}{%endblock%}</title>
		<link rel="stylesheet" type="text/css" href="{%static 'vendor/bootstrap/css/bootstrap.min.css'%}">
		<link rel="stylesheet" type="text/css" href="{%static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css'%}">
		{%block link%}{%endblock%}
	</head>
	<body  style="font-family:'Nunito Sans';letter-spacing: 1px;">
		<div class="container-fluid mb-3">
			{%block content%}
			{%endblock%}
		</div>
	</body>
	<script src="{%static 'vendor/jquery/jquery-3.2.1.min.js'%}"></script>
	<script src="{%static 'vendor/bootstrap/js/bootstrap.min.js'%}"></script>
	{%block script%}
	{%endblock%}
</html>

templates/base_templates/dashboard.html
{%extends 'base_templates/base.html'%}
{%block title%}
  Dashboard
{%endblock%}
{%block content%}
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-8">
        <hr>
        <div class="row">
          <div class="col-sm-6">
            <div class="row">
              <div class="col-sm-6">
                <div class="card bg-danger mb-3" style="max-width: 18rem;">
                  <div class="card-body text-center">
                    <a href="{%url 'cust:view'%}" class="text-white ">
                      <h5 class="card-title"><i class="fa fa-group" style="font-size:24px"></i></h5>
                      <p class="card-text">customer</p>
                    </a>
                  </div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="card  bg-danger mb-3" style="max-width: 18rem;">
                  <div class="card-body text-center">
                    <a href="{%url 'item:view'%}" class="text-white">
                      <h5 class="card-title"><i class="fa fa-list-alt" style="font-size:24px"></i></h5>
                      <p class="card-text">item</p>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <div class="card bg-primary mb-3" style="max-width: 18rem;">
                  <div class="card-body text-center">
                    <a href="{%url 'item:new_bill'%}" class=" text-white">
                      <h5 class="card-title"><i class="fa fa-file-text" style="font-size:24px"></i></h5>
                      <p class="card-text">Bill</p>
                    </a>
                  </div>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="card  bg-primary mb-3" style="max-width: 18rem;">
                  <div class="card-body text-center">
                    <a href="{%url 'payment:pay'%}" class="text-white">
                      <h5 class="card-title"><i class="fa fa-rupee" style="font-size:24px"></i></h5>
                      <p class="card-text">Payment</p>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <div class="card  bg-info mb-3" style="max-width: 18rem;">
                  <div class="card-header mb-3">
                    <div class="text-white text-center">
                      <h5 class="card-title"><i class="fa fa-strikethrough" style="font-size:24px"></i></h5>
                      <p class="card-text">Shortcuts</p>
                    </div>
                  </div>
                  <ul class="list-group pl-2 pb-3" style="list-style: none;">
                    <li><a href="#" class="text-white">Add Weekly Payment</a></li>
                    <li><a href="#" class="text-white">Add New Stock</a></li>
                    <li><a href="#" class="text-white">--------</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="card  bg-info mb-3" style="max-width: 18rem;">
                  <div class="card-header mb-3">
                    <div class="text-white text-center">
                      <h5 class="card-title"><i class="fa fa-paperclip" style="font-size:24px"></i></h5>
                      <p class="card-text">Report</p>
                    </div>
                  </div>
                  <ul class="list-group pl-2 pb-3" style="list-style: none;">
                    <li><a href="{%url 'item:view_bill'%}" class="text-white">Stock Report</a></li>
                    <li><a href="{%url 'payment:view'%}" class="text-white">Payment Report</a></li>
                    <li><a href="{%url 'report:report'%}" class="text-white">Customer Ledger</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="row">
              <div class="col-sm-12">
                <div class="input-group input-group-sm mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-sm">Customer no</span>
                  </div>
                  <input type="number" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm" id="balance_account">
                </div>
                <div class="input-group input-group-sm mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text"  id="amount_output">Amount</span>
                  </div>
                  <input type="text" class="form-control" id="balance_output" aria-label="Small" aria-describedby="inputGroup-sizing-sm" placeholder="Enter Customer account no above to know balance" disabled>
                </div>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-12 text-center"><h5><b>Stock</b></h5></div>
            </div>
              <ul class="list-group">
                {% for item in object_list %}
                  <li class="list-group-item d-flex justify-content-between align-items-center" style="padding:.55rem">
                    {{item.item.name}}
                    <span class="badge badge-primary badge-pill">{{item.quantity_left}}</span>
                  </li>
                {% endfor %}
              </ul>
            </div>
        </div>
      </div>
      <div class="col-sm-2"></div>
    </div>
  </div>
{%endblock%}
{% block script%}
  <script type="text/javascript">
    var input = document.getElementById('balance_account');
    input.addEventListener("keyup", function(event) {
      if (event.keyCode === 13) {
        event.preventDefault();
        var id = input.value;
        $.ajax({
            url: "{%url 'payment:apibalance'%}",
            data: {'id':id},
            datatype: 'json',
            success: function(data){
              var model = JSON.parse(data);
              if (model.responce) {
                $('#amount_output').html(model.amount);
                document.getElementById('balance_output').placeholder = model.name
              }
              else {
                $('#amount_output').html("Error");
                document.getElementById('balance_output').placeholder = model.data
              }
            }
        });
      }
    });
  </script>
{%endblock%}

templates/base_templates/navbar.html
{%load static%}
<style media="screen">
  @font-face {
    font-family: 'Indie Flower';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: local('Indie Flower'), local('IndieFlower'), url({%static 'fonts/m8JVjfNVeKWVnh3QMuKkFcZVaUuH.woff2'%}) format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  }
  /* vietnamese */
  @font-face {
    font-family: 'Nunito Sans';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: local('Nunito Sans Regular'), local('NunitoSans-Regular'), url({% static 'fonts/pe0qMImSLYBIv1o4X1M8cceyI9tScg.woff2'%}) format('woff2');
    unicode-range: U+0102-0103, U+0110-0111, U+1EA0-1EF9, U+20AB;
  }
  /* latin-ext */
  @font-face {
    font-family: 'Nunito Sans';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: local('Nunito Sans Regular'), local('NunitoSans-Regular'), url({%static 'fonts/pe0qMImSLYBIv1o4X1M8ccezI9tScg.woff2'%}) format('woff2');
    unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
  }
  /* latin */
  @font-face {
    font-family: 'Nunito Sans';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: local('Nunito Sans Regular'), local('NunitoSans-Regular'), url({%static 'fonts/pe0qMImSLYBIv1o4X1M8cce9I9s.woff2'%}) format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
  }
</style>
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand ml-5" href="{%url 'homepage'%}">
    <span style="font-family:'Indie Flower';font-weight:bold;letter-spacing: 1px;color:green">Accounts Management</span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    {% if request.user.is_authenticated %}
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <li><a href="{%url 'password_change'%}" class="nav-link" style="font-family:'Indie Flower';font-weight:bold;color:blue;">Change Password</a></li>
        </li>
        <li class="nav-item">
          <li><a href="{%url 'logout'%}" class="nav-link" style="font-family:'Indie Flower';font-weight:bold;color:blue;">Log Out</a></li>
        </li>
      </ul>
    {% endif %}
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>