dairy_site/urls.py
from django.urls import path,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',views.homePage,name='homepage'),
    path('customer/',include('customer.urls',namespace='cust')),
    path('item/',include('item_register.urls',namespace='item')),
    path('pay/',include('payment.urls',namespace='payment')),
    path('report/',include('reports.urls',namespace='report')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item_register/urls.py
from django.urls import path
from . import views

app_name='item_register'
urlpatterns = [
    path('add/',views.AddItem.as_view(),name='add'),
    path('view/',views.ViewItem.as_view(),name='view'),
    path('update/<int:pk>',views.UpdateItem.as_view(),name='update'),
    path('delete/<int:pk>',views.DeleteItem.as_view(),name='delete'),
    path('add_bill/',views.AddBill.as_view(),name='add_bill'),
    path('tempitem/',views.TempItemCreateView.as_view(),name='addtempitem'),
    path('tempitemupdate/<int:pk>',views.TempItemEditView.as_view(),name='edittempitem'),
    path('tempitemdelete/<int:pk>',views.TempItemDeleteView.as_view(),name='deletetempitem'),
    path('newbill/',views.NewBill,name='new_bill'),
    path('viewbills/',views.ViewBill.as_view(),name='view_bill'),
    path('deltebills/<int:pk>',views.DeleteBill.as_view(),name='delete_bill'),
    path('api/update',views.updateList,name='list'),
    path('blank/',views.blankPage,name='blank'),
    # path('stockregister/',views.StockRegister,name='stock_register'),
]

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'
urlpatterns = [
    path('pay/',views.AddTransection.as_view(),name='pay'),
    path('view/',views.ViewTransection.as_view(),name='view'),
    path('delete/<int:pk>',views.DeleteTransection.as_view(),name='delete'),
    path('api/balance',views.giveBalance,name='apibalance'),
]

item_register/models.py
from django.db import models
from django.utils import timezone
from customer.models import Customer
from django.db.models.signals import pre_delete,post_save,pre_save,pre_delete
from django.dispatch import receiver

class Item(models.Model):
    item_id = models.IntegerField(unique=True,null=True)
    name = models.CharField(max_length=25)

    class Meta:
        ordering = ['item_id']

    def __str__(self):
        return str(str(self.item_id) +" "+ str(self.name))

class Item_detail(models.Model):
    item = models.ForeignKey(Item,on_delete=models.PROTECT)
    quantity = models.IntegerField()
    price = models.IntegerField()

class temp_Item_detail(models.Model):
    item = models.ForeignKey(Item,on_delete=models.PROTECT)
    quantity = models.IntegerField()
    price = models.IntegerField()


class Bill(models.Model):
    date = models.DateField(default=timezone.now,blank = True)
    bill_no = models.CharField(unique=True,max_length=10)
    customer = models.ForeignKey(Customer,on_delete=models.PROTECT)
    items = models.ManyToManyField(Item_detail)
    total_amount = models.IntegerField(blank=True,null=True)
    is_buy = models.BooleanField(default=False)
    remarks = models.CharField(max_length=255,blank=True,null=True)

    class Meta:
        ordering = ['date']

class Item_stock(models.Model):
    date_stock_update = models.DateField(default=timezone.now,blank=True)
    item = models.ForeignKey(Item,on_delete=models.PROTECT)
    recent_stock = models.IntegerField()
    quantity_left = models.IntegerField()

@receiver(post_save,sender=Item)
def stockItemAdd(sender,**kwargs):
    if kwargs['created']:
        data = kwargs['instance']
        Item_stock.objects.create(
            item = data,
            recent_stock = 0,
            quantity_left = 0
        )

@receiver(post_save,sender=Bill)
def stockUpdate(sender,**kwargs):
    if kwargs['created']:
        data = kwargs['instance']
        obj = Bill.objects.get(id=data.id)
        for item in temp_Item_detail.objects.all():
            stock = Item_stock.objects.get(item = item.item)
            if obj.is_buy:
                stock.quantity_left += item.quantity
            else:
                stock.quantity_left -= item.quantity
            stock.save()

@receiver(pre_delete,sender=Bill)
def updateStockOnBill(sender,**kwargs):
    obj = kwargs['instance']
    for item in obj.items.all():
        stock = Item_stock.objects.get(item = item.item)
        if obj.is_buy:
            stock.quantity_left -= item.quantity
        else:
            stock.quantity_left += item.quantity
        stock.save()

@receiver(pre_delete,sender=Bill)
def removeItemsOfBills(sender,**kwargs):
    data = kwargs['instance']
    for item in data.items.all():
        Item_detail.objects.get(id = item.pk).delete()

payment/models.py
from django.db import models
from customer.models import Customer
from django.utils import timezone
from item_register.models import Bill
from customer.models import Customer
from django.db.models.signals import pre_delete,post_save,pre_save,pre_delete
from django.dispatch import receiver

class Transections(models.Model):
    date = models.DateField(default=timezone.now,blank=True)
    trans_id = models.CharField(max_length=10,unique=True,null=True)
    customer = models.ForeignKey(Customer,on_delete=models.PROTECT)
    credit = models.BooleanField(default=False)
    amount = models.IntegerField()
    remarks = models.CharField(max_length=255,blank=True,null=True)

    class Meta:
        ordering = ['date']

class Balance(models.Model):
    date = models.DateField(default=timezone.now,blank=True)
    customer = models.ForeignKey(Customer,on_delete=models.PROTECT)
    balance = models.IntegerField()

@receiver(post_save,sender=Customer)
def addCustomertobalance(sender,**kwargs):
    if kwargs['created']:
        data = kwargs['instance']
        Balance.objects.create(
            customer = data,
            balance = 0
        )
    return 0

@receiver(pre_delete,sender=Transections)
def removeBalance(sender,**kwargs):
    obj = kwargs['instance']
    balance = Balance.objects.get(customer=obj.customer)
    if obj.credit:
        balance.balance -= obj.amount
    else:
        balance.balance += obj.amount
    balance.save()


@receiver(post_save,sender=Transections)
def updateBalance(sender,**kwargs):
    if kwargs['created']:
        obj = kwargs['instance']
        balance = Balance.objects.get(customer=obj.customer)
        if obj.credit:
            balance.balance += obj.amount
        else:
            balance.balance -= obj.amount
        balance.save()

@receiver(pre_delete,sender=Bill)
def billbalanceremove(sender,**kwargs):
    data = kwargs['instance']
    obj = Bill.objects.get(id=data.id)
    Transections.objects.get(trans_id = 'BL'+str(obj.bill_no)).delete()

item_register/views.py
from django.views.generic import CreateView,ListView,UpdateView,DeleteView,FormView
from django.urls import reverse_lazy
from django.shortcuts import redirect,render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Item,Bill,temp_Item_detail,Item_detail
from django import forms
from customer.models import Customer
from payment.models import Balance,Transections
from django.http import HttpResponse,JsonResponse
from django.core import serializers
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.contrib import messages
import json

class AddItem(LoginRequiredMixin,CreateView):
    model = Item
    template_name = 'add_item.html'
    fields = ['item_id','name']
    success_url = reverse_lazy('item:blank')

class ViewItem(LoginRequiredMixin,ListView):
    model = Item
    paginate_by = 50
    template_name = 'view_item.html'

    def get_context_data(self, **kwargs):
        context = super(ViewItem, self).get_context_data(**kwargs)
        query = Item.objects.all().order_by('item_id')
        paginator = Paginator(query, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            file_exams = paginator.page(page)
        except PageNotAnInteger:
            file_exams = paginator.page(1)
        except EmptyPage:
            file_exams = paginator.page(paginator.num_pages)

        context['object_list'] = file_exams
        return context

class UpdateItem(LoginRequiredMixin,UpdateView):
    model = Item
    fields = ['item_id','name']
    template_name = 'update_item.html'
    success_url = reverse_lazy('item:blank')

class DeleteItem(LoginRequiredMixin,DeleteView):
    model = Item
    success_url = reverse_lazy('item:view')
    template_name = 'delete_item.html'

class AddBill(LoginRequiredMixin,CreateView):
    model = Bill
    template_name = 'add_bill.html'
    fields = ['date','bill_no','customer','is_buy','remarks']
    success_url = reverse_lazy('homepage')

    def form_valid(self,form):
        items = temp_Item_detail.objects.all()
        if not temp_Item_detail.objects.all().exists():
            messages.error(self.request,"Add Some Items")
            return redirect('item:add_bill')
        bill = form.save()
        total_amount = 0
        for item in items:
            total_amount += (item.price*item.quantity)
            temp = Item_detail.objects.create(
                item = item.item,
                quantity =item.quantity,
                price = item.price,
            )
            bill.items.add(temp)
        bill.total_amount = total_amount
        bill.save()
        Transections.objects.create(
            date = bill.date,
            trans_id = 'BL'+str(bill.bill_no),
            customer = bill.customer,
            credit = bill.is_buy,
            amount = bill.total_amount,
            remarks = bill.remarks
        )
        return redirect('homepage')

    def get_context_data(self,**kwargs):
        form = super(AddBill, self).get_context_data(**kwargs)
        item = temp_Item_detail.objects.all()
        return {'items':item,'form':form}

class ViewBill(LoginRequiredMixin,ListView):
    model = Bill
    paginate_by = 70
    template_name = 'viewbill.html'

    def get_context_data(self, **kwargs):
        item = self.request.GET.get('item')
        query = Bill.objects.all()
        if item == None:
            item = 0
        if item == '1':
            query = query.filter(is_buy = True)
        elif item == '2':
            query = query.filter(is_buy = False)
        context = super(ViewBill, self).get_context_data(**kwargs)
        paginator = Paginator(query, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            file_exams = paginator.page(page)
        except PageNotAnInteger:
            file_exams = paginator.page(1)
        except EmptyPage:
            file_exams = paginator.page(paginator.num_pages)

        context['object_list'] = file_exams
        context['active'] = item
        return context

class DeleteBill(LoginRequiredMixin,DeleteView):
    model = Bill
    template_name = 'delete_bill.html'
    success_url = reverse_lazy('item:blank')

class TempItemCreateView(LoginRequiredMixin,CreateView):
    template_name = 'add_temp_item.html'
    model = temp_Item_detail
    fields = ['item','quantity','price']
    success_url = reverse_lazy('item:blank')

class TempItemEditView(LoginRequiredMixin,UpdateView):
    model = temp_Item_detail
    template_name = 'update_temp_item.html'
    fields = ['item','quantity','price']
    success_url = reverse_lazy('item:blank')

class TempItemDeleteView(LoginRequiredMixin,DeleteView):
    model= temp_Item_detail
    template_name = 'delete_temp_item.html'
    success_message = 'item deleted'
    success_url = reverse_lazy('item:blank')

@login_required
def NewBill(request):
    items = temp_Item_detail.objects.all()
    items.delete()
    return redirect('item:add_bill')

@login_required
def updateList(request):
    if request.method == 'GET':
        query = temp_Item_detail.objects.all()
        data = []
        for item in query:
            data.append(
                {
                    'pk': item.pk,
                    'fields': {"item": item.item.name, "quantity": item.quantity, "price": item.price}
                }
            )
        return HttpResponse(json.dumps(data))
    return JsonResponse({'error':'some problem with server RETRY!'})

@login_required
def blankPage(request):
    return render(request,'blank.html')

item_register/templates/add_bill.html
{%extends 'base_templates/base.html'%}
{% load static %}
{%block title%}Add Bill{%endblock%}
{%block content%}
<style media="screen">
.table td, .table th {
  padding: 0.35rem;
  vertical-align: top;
  border-top: 1px solid #dee2e6;
}
</style>
<hr>
  <div class="row mb-4">
    <div class="col-sm-2"></div>
    <div class="col-sm-8 text-center text-muted"> Add Bill</div>
  </div>
  <div class="row">
    <div class="col-md-12 text-info">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <form  method="post">
        {%csrf_token%}
        {{ form.form.non_field_errors }}
        <div class="form-row">
          <div class="col-md-2 mb-3">
            <label for="{{ form.form.date.id_for_label }}">Date</label>
            {{form.form.date}}
            {%if form.form.date.errors %}
              <div class="invalid-tooltip" style="display:block">
                {{ form.form.date.errors }}
              </div>
            {%endif%}
          </div>
          <div class="col-md-2 mb-3">
            <label for="{{ form.form.bill_no.id_for_label }}">Bill ID</label>
            {{form.form.bill_no}}
            {%if form.form.bill_no.errors %}
              <div class="invalid-tooltip" style="display:block">
                {{ form.form.bill_no.errors }}
              </div>
            {%endif%}
          </div>
          <div class="col-md-2 mb-3">
            <label for="id_customer">Customer Id</label>
            <input type="number" class="form-control" id="customer_id" required>
            <input type="hidden" name="customer" value="{{form.form.customer.value}}" id="id_customer">
            {%if form.form.customer.errors %}
              <div class="invalid-tooltip" style="display:block">
                {{ form.form.customer.errors }}
              </div>
            {%endif%}
          </div>
          <div class="col-md-4 mb-3">
            <label for="{{ form.form.remarks.id_for_label }}">Remarks</label>
            {{form.form.remarks}}
            {%if form.form.remarks.errors %}
              <div class="invalid-tooltip" style="display:block">
                {{ form.form.remarks.errors }}
              </div>
            {%endif%}
          </div>
          <div class="col-md-2 mb-3 mt-4">
            {{ form.form.is_buy.errors }}
            <div class="custom-control custom-checkbox">
              {{form.form.is_buy}}
              <!-- <input type="checkbox" class="custom-control-input" id="id_credit" name="credit"> -->
              <label class="custom-control-label" for="{{ form.form.is_buy.id_for_label }}">Buy</label>
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="col-md-4 mb-3">
            <!-- <label for="validationTooltip02">Customer Name</label> -->
            <input type="text" class="form-control" value="customer name" style="color:blue" id="customer_name" disabled>
            <div class="valid-tooltip">
              Looks good!
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="col-md-11">
            <div class="table-responsive">
              <table class="table table-striped border-bottom" style="font-size:12px;">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Item</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col">amount</th>
                    <th scope="col" colspan="2">  <span style="cursor:pointer;color:green" onclick="openwindow(0,0)">add item</th>
                  </tr>
                </thead>
                <tbody id="data">
                  {%for item in items %}
                    <tr>
                      <th scope="row">{{forloop.counter}}</th>
                      <td>{{item.item.name}}</td>
                      <td>{{item.quantity}}</td>
                      <td>{{item.price}}</td>
                      <td></td>
                      <td>
                        <span style="cursor:pointer;color:green" onclick="openwindow(1,{{item.pk}})" id="{{item.pk}}-update" data-url="{%url 'item:edittempitem' item.pk %}">
                          <i class="fa fa-edit"></i>
                        </span>
                      </td>
                      <td>
                        <span style="cursor:pointer;color:red" onclick="openwindow(2,{{item.pk}})" id="{{item.pk}}-delete" data-url="{%url 'item:deletetempitem' item.pk %}">
                          <i class="fa fa-trash"></i>
                        </span>
                      </td>
                    </tr>
                  {% empty %}
                    <tr><th colspan="6" class="text-center text-info">No Items yet.</th></tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="form-row mb-3 ml-1">
          <div class="col-md-6">Total Amount <span id='total_amount' class="badge badge-info"></span></div>
          <div class="col-md-5 text-right">
            <button class="btn btn-primary" type="submit">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{%endblock%}
{%block script%}
  <script type="text/javascript">
  $('#id_date').addClass('form-control')
  $('#id_bill_no').addClass('form-control')
  $('#id_remarks').addClass('form-control')
  $('#id_bill_no').prop('type','number')
  $('#id_is_buy').addClass('custom-control-input')
  var $initial = $('#id_customer');
  var typingTimer;                //timer identifier
  var doneTypingInterval = 300;  //time in ms, 5 second for example
  var $input = $('#customer_id');

  if ($initial.val()) {
    var $input = $('#id_customer');
    doneTyping();
    var $input = $('#customer_id');
    $input.val($initial.val())
  }
  //on keyup, start the countdown
  $input.on('keyup', function () {
    clearTimeout(typingTimer);
    typingTimer = setTimeout(doneTyping, doneTypingInterval);
  });

  //on keydown, clear the countdown
  $input.on('keydown', function () {
    clearTimeout(typingTimer);
  });

  //user is "finished typing," do something
  updateamount()
  function updateamount(){
    var total_amount = 0;
    var $table = $('tbody#data').children().each(function(id,element){
       val1 = $(this).children().eq(2).html();
       val2 = $(this).children().eq(3).html();
       $(this).children().eq(4).html(val1*val2);
       total_amount += val1*val2;
    });
    $('#total_amount').html(total_amount);
  }

  function loadData(){
    $.ajax(
      {
        type:"GET",
        url:"{%url 'item:list'%}",
        success:function(data){
          var model = JSON.parse(data);
          var syntex
          if (!model[0]) {
              syntex += '<tr><th colspan="6" class="text-center text-info">No Items yet.</th></tr>'
          }
          for (var bit in model) {
            no = parseFloat(bit)+1;
            id = model[bit].pk;
            syntex+=  '<tr>'
            syntex+=  '<th scope="row">'+no+'</th>'
            syntex+=  '<td>'+String(model[bit].fields.item)+'</td>'
            syntex+=  '<td>'+String(model[bit].fields.quantity)+'</td>'
            syntex+=  '<td>'+String(model[bit].fields.price)+'</td>'
            syntex+=  '<td></td>'
            syntex+=  '<td>'
            syntex+=  '<span style="cursor:pointer;color:green" onclick="openwindow(1,'+id+')" id="'+id+'-update" data-url="/item/tempitemupdate/'+id+'">'
            syntex+=  '<i class="fa fa-edit"></i>'
            syntex+=  '</span>'
            syntex+=  '</td>'
            syntex+=  '<td>'
            syntex+=  '<span style="cursor:pointer;color:red" onclick="openwindow(2,'+id+')" id="'+id+'-delete" data-url="/item/tempitemdelete/'+id+'">'
            syntex+=  '<i class="fa fa-trash"></i>'
            syntex+=  '</span>'
            syntex+=  '</td>'
            syntex+=  '</tr>'
          }
          $('#data').html("");
          $('#data').html(syntex);
          updateamount()
        }
      }
    )
  }
  function doneTyping () {
    var id = $input.val();
    if (!id) {
      $('#customer_name').val('Customer Name');
      $('#customer_name').css('color','blue');
      $('#id_customer').val('None');
    }
    else {
      $.ajax({
          url: "{%url 'payment:apibalance'%}",
          data: {'id':id},
          datatype: 'json',
          success: function(data){
            var model = JSON.parse(data);
            if (model.responce) {
              $('#customer_name').val(model.name);
              $('#id_customer').val(model.id);
              $('#customer_name').css('color','green');
            }
            else {
              $('#id_customer').val('None');
              $('#customer_name').val(model.data);
              $('#Customer_name').css('color','red');
            }
          }
      });
    }
  }
  function openwindow(i,id){
    var url;
    if (i==0) {
      url = "{%url 'item:addtempitem'%}";
    }
    else if (i==1) {
      var opt = document.getElementById(id+'-update');
      url = opt.dataset.url;
    }
    else {
      var opt = document.getElementById(id+'-delete');
      url = opt.dataset.url;
    }
    newwindow = window.open(url,"Form","width=500,height=350,left=400,top=200");
    newwindow.loadData;
  }
</script>
{%endblock%}

item_register/templates/add_item.html
{%extends 'base_templates/base_without_navbar.html'%}
{%block title%}Add Item{%endblock%}
{%block content%}
  <div class="container mt-3 mr-0">
    <div class="row">
      <div class="col-sm-12">
        <h5 class="text-muted mb-3">Add Item</h5>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <div class="col-sm-6">
          {{form}}
          <button type="submit" name="button" class="btn btn-info mt-3">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{%endblock%}
{%block script%}
<script type="text/javascript">
  $('#id_item_id').addClass('form-control');
  $('#id_name').addClass('form-control');
</script>
{%endblock%}

item_register/templates/add_temp_item.html
{%extends 'base_templates/base_without_navbar.html'%}
{%block title%}Add Item{%endblock%}
{%block content%}
  <div class="container mt-3 mr-0">
    <div class="row">
      <div class="col-sm-12">
        <h5 class="text-muted mb-3">Add Item</h5>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <div class="col-sm-6">
          {{form}}
          <button type="submit" name="button" class="btn btn-info mt-3">Add</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{%endblock%}
{%block script%}
<script type="text/javascript">
  $('#id_item').addClass('form-control');
  $('#id_quantity').addClass('form-control');
  $('#id_price').addClass('form-control');
</script>
{%endblock%}

item_register/templates/blank.html
<script type="text/javascript">
  opener.loadData();
  window.close();
</script>

item_register/templates/delete_item.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

item_register/templates/update_item.html
{%extends 'base_templates/base_without_navbar.html'%}
{%block title%}Edit Item{%endblock%}
{%block content%}
  <div class="container mt-3 mr-0">
    <div class="row">
      <div class="col-sm-12">
        <h5 class="text-muted mb-3">Update Item</h5>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <div class="col-sm-6">
          {{form}}
          <button type="submit" name="button" class="btn btn-info mt-3">Update</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{%endblock%}
{%block script%}
<script type="text/javascript">
  $('#id_item_id').addClass('form-control');
  $('#id_name').addClass('form-control');
</script>
{%endblock%}

item_register/templates/update_temp_item.html
{%extends 'base_templates/base_without_navbar.html'%}
{%block title%}Edit Item{%endblock%}
{%block content%}
  <div class="container mt-3 mr-0">
    <div class="row">
      <div class="col-sm-12">
        <h5 class="text-muted mb-3">Add Item</h5>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <div class="col-sm-6">
          {{form}}
          <button type="submit" name="button" class="btn btn-info mt-3">Update</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{%endblock%}
{%block script%}
<script type="text/javascript">
  $('#id_item').addClass('form-control');
  $('#id_quantity').addClass('form-control');
  $('#id_price').addClass('form-control');
</script>
{%endblock%}

item_register/templates/view_item.html
{% extends 'base_templates/base.html'%}
{%block title%} Items {%endblock%}
{%block content%}
<style media="screen">
.table td, .table th {
  padding: 0.35rem;
  vertical-align: top;
  border-top: 1px solid #dee2e6;
}
</style>
<hr>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-1"></div>
      <div class="col-sm-10">
        <div class="row mb-3">
          <div class="col-sm-4 text-muted"><h4>Items list</h4></div>
          <div class="col-sm-4"></div>
          <div class="col-sm-4 text-muted text-right"><span class="btn btn-primary" style="font-size:11px" id="add_item" onclick="openform(0,0)" data-url="{%url 'item:add'%}">Add Item</span></div>
        </div>
        <div class="row border-top border-bottom mb-3" style="background-color:#f4f4ff">
          <div class="col-sm-4">
            <div class="input-group input-group-sm mt-2 mb-2">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroup-sizing-sm"><i class="fa fa-search"></i></span>
                </div>
                <input type="text" id="data_input"class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="table-responsive">
            <table class="table table-striped" style="font-size:12px;">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">id</th>
                  <th scope="col">Name</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                {% for item in object_list %}
                  <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{ item.item_id }} </td>
                    <td>{{ item.name }}</td>
                    <td>
                      <span id="edit-{{item.id}}" onclick="openform(1,{{item.id}})" data-url="{%url 'item:update' item.id%}" style="color:#FFA500;"><i class="fa fa-edit"></i></span>
                      <!-- <a href="{%url 'item:delete' item.id%}"><i class="fa fa-trash-o"></i></a> -->
                    </td>
                  </tr>
                {% empty %}
                    <tr><td colspan="4" class="text-center">No Items yet.</td></tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="row">
          <nav aria-label="...">
            <ul class="pagination pagination-sm">
              {% for item in "x"|ljust:object_list.paginator.num_pages %}
                {%if forloop.counter == object_list.number %}
                  <li class="page-item disabled">
                    <a class="page-link" href="?page={{forloop.counter}}" tabindex="-1">{{forloop.counter}}</a>
                  </li>
                {%else%}
                  <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                {%endif%}
              {% endfor %}
            </ul>
          </nav>
        </div>
      </div>
      <div class="col-sm-1"></div>
    </div>
  </div>
{%endblock%}
{%block script%}
<script type="text/javascript">
  function openform(type,id){
    if (type == 0) {
      url = document.getElementById('add_item').dataset.url
    }else{
      url = document.getElementById('edit-'+id).dataset.url
    }
    newwindow = window.open(url,"Form","width=400,height=300,left=400,top=200");
    newwindow.loadData()
  }

  function loadData(){
    window.location.reload();
  }
</script>
{%endblock%}