customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'
urlpatterns = [
    path('add/',views.addCustomer.as_view(),name='add'),
    path('view/',views.CustomerListView.as_view(),name='view'),
    path('delete/<int:pk>',views.CustomerDeleteView.as_view(),name='delete'),
    path('update/<int:pk>',views.CustomerUpdateView.as_view(),name='update'),
]

dairy_site/urls.py
from django.urls import path,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',views.homePage,name='homepage'),
    path('customer/',include('customer.urls',namespace='cust')),
    path('item/',include('item_register.urls',namespace='item')),
    path('pay/',include('payment.urls',namespace='payment')),
    path('report/',include('reports.urls',namespace='report')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'
urlpatterns = [
    path('pay/',views.AddTransection.as_view(),name='pay'),
    path('view/',views.ViewTransection.as_view(),name='view'),
    path('delete/<int:pk>',views.DeleteTransection.as_view(),name='delete'),
    path('api/balance',views.giveBalance,name='apibalance'),
]

customer/models.py
from django.db import models
from django.utils import timezone

class Customer(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    cust_id = models.IntegerField(unique=True,null=True)
    name = models.CharField(max_length=25)
    father_or_husband_name = models.CharField(max_length=25)
    village = models.CharField(max_length=25)
    mobile_no = models.IntegerField(null=True,blank=True)

    class Meta:
        ordering = ['cust_id']

    def __str__(self):
        return str(str(self.cust_id)+" "+str(self.name))

customer/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Customer
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger


class addCustomer(LoginRequiredMixin,CreateView):
    template_name = 'add_customer.html'
    model = Customer
    fields = ['cust_id','name','father_or_husband_name','village','mobile_no']
    success_url = reverse_lazy('item:blank')

class CustomerListView(LoginRequiredMixin,ListView):
    model = Customer
    ordering = ['cust_id']
    paginate_by = 50
    template_name = 'customer_list.html'

    def get_context_data(self, **kwargs):
        context = super(CustomerListView, self).get_context_data(**kwargs)
        query = Customer.objects.all().order_by('cust_id')
        paginator = Paginator(query, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            file_exams = paginator.page(page)
        except PageNotAnInteger:
            file_exams = paginator.page(1)
        except EmptyPage:
            file_exams = paginator.page(paginator.num_pages)

        context['object_list'] = file_exams
        return context

class CustomerUpdateView(LoginRequiredMixin,UpdateView):
    model = Customer
    fields = ['cust_id','name','father_or_husband_name','village','mobile_no']
    success_url = reverse_lazy('item:blank')
    template_name = 'customer_update.html'

class CustomerDeleteView(LoginRequiredMixin,DeleteView):
    model = Customer
    success_url = reverse_lazy('cust:view')
    template_name = 'customer_delete.html'

customer/templates/add_customer.html
{%extends 'base_templates/base_without_navbar.html'%}
{%block content%}
  <div class="container mt-3 mr-0">
    <div class="row">
      <div class="col-sm-12">
        <h5 class="text-muted mb-3">Add Customer</h5>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <div class="col-sm-6">
          {{form}}
          <button type="submit" name="button" class="btn btn-info mt-3">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{%endblock%}
{%block script%}
<script type="text/javascript">
  $('#id_cust_id').addClass('form-control');
  $('#id_name').addClass('form-control');
  $('#id_father_or_husband_name').addClass('form-control');
  $('#id_village').addClass('form-control');
  $('#id_mobile_no').addClass('form-control');
</script>
{%endblock%}

customer/templates/customer_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

customer/templates/customer_list.html
{% extends 'base_templates/base.html'%}
{%block title%} Customers {%endblock%}
{%block content%}
<style media="screen">
.table td, .table th {
  padding: 0.35rem;
  vertical-align: top;
  border-top: 1px solid #dee2e6;
}
</style>
<hr>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-1"></div>
      <div class="col-sm-10">
        <div class="row mb-3">
          <div class="col-sm-4 text-muted"><h4>Customers list</h4></div>
          <div class="col-sm-4"></div>
          <div class="col-sm-4 text-muted text-right"><span class="btn btn-primary" style="font-size:11px" data-url="{%url 'cust:add'%}" onclick="openform(0,0)" id="add_customer">Add Customer</span></div>
        </div>
        <div class="row border-top border-bottom mb-3" style="background-color:#f4f4ff">
          <div class="col-sm-4">
            <div class="input-group input-group-sm mt-2 mb-2">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroup-sizing-sm"><i class="fa fa-search"></i></span>
                </div>
                <input type="text" id="data_input"class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="table-responsive">
            <table class="table table-striped" style="font-size:12px;">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">id</th>
                <th scope="col">Name</th>
                <th scope="col">Father/Husband Name</th>
                <th scope="col">Village</th>
                <th scope="col">Mobile no</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              {% for customer in object_list %}
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                  <td>{{ customer.cust_id }} </td>
                  <td>{{ customer.name }}</td>
                  <td>{{customer.father_or_husband_name}}</td>
                  <td>{{customer.village}}</td>
                  <td>{{customer.mobile_no}}</td>
                  <td>
                    <span id="edit-{{customer.id}}" onclick="openform(1,{{customer.id}})" data-url="{%url 'cust:update' customer.id%}" style="color:#FFA500;"><i class="fa fa-edit"></i></span>
                    <!-- <a href="{%url 'cust:delete' customer.id%}"><i class="fa fa-trash-o"></i></a> -->
                  </td>
                </tr>
              {% empty %}
                  <tr><td colspan="7" class="text-center">No Customers yet.</td></tr>
              {% endfor %}
            </tbody>
          </table>
          </div>
        </div>
        <div class="row">
          <nav aria-label="...">
            <ul class="pagination pagination-sm">
              {% for item in "x"|ljust:object_list.paginator.num_pages %}
                {%if forloop.counter == object_list.number %}
                  <li class="page-item disabled">
                    <a class="page-link" href="?page={{forloop.counter}}" tabindex="-1">{{forloop.counter}}</a>
                  </li>
                {%else%}
                  <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                {%endif%}
              {% endfor %}
            </ul>
          </nav>
        </div>
      </div>
      <div class="col-sm-1"></div>
    </div>
  </div>
{%endblock%}
{%block script%}
<script type="text/javascript">
  function openform(type,id){
    if(type == 0){
      url = document.getElementById('add_customer').dataset.url
    }
    else {
      url = document.getElementById('edit-'+id).dataset.url
    }
    newwindow = window.open(url,"Form","width=500,height=500,left=400,top=100");
    newwindow.loadData()
  }

  function loadData(){
    window.location.reload();
  }
</script>
{%endblock%}

customer/templates/customer_update.html
{%extends 'base_templates/base_without_navbar.html'%}
{%block content%}
  <div class="container mt-3 mr-0">
    <div class="row">
      <div class="col-sm-12">
        <h5 class="text-muted mb-3">Update Customer</h5>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <div class="col-sm-6">
          {{form}}
          <button type="submit" name="button" class="btn btn-info mt-3">Update</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{%endblock%}
{%block script%}
<script type="text/javascript">
  $('#id_cust_id').addClass('form-control');
  $('#id_name').addClass('form-control');
  $('#id_father_or_husband_name').addClass('form-control');
  $('#id_village').addClass('form-control');
  $('#id_mobile_no').addClass('form-control');
</script>
{%endblock%}